import React, { useState } from 'react';
import { getJoursFerie, calculerContratBetty, getContrastYIQ, parseHeureSaisie, formatHeureMinutes, executeImport } from './utils';

export const SetupWizard = ({ onComplete, t }) => {
  const nomsJours = ['DIM', 'LUN', 'MAR', 'MER', 'JEU', 'VEN', 'SAM'];
  const [step, setStep] = useState(1);
  const [periodes, setPeriodes] = useState([]);
  const [agents, setAgents] = useState([]);
  const [postes, setPostes] = useState([]);

  const [anneeScolaireDeBase, setAnneeScolaireDeBase] = useState(new Date().getMonth() >= 6 ? new Date().getFullYear() : new Date().getFullYear() - 1);
  const [zone, setZone] = useState("Zone C");
  const [isFetchingDates, setIsFetchingDates] = useState(false);
  const [dotation, setDotation] = useState(0);

  const [formPeriode, setFormPeriode] = useState({ nom: '', debut: '', fin: '', type: 'vacances' });
  const [formAgent, setFormAgent] = useState({ nom: '', quotite: '100', estEtudiant: false, hContrat: calculerContratBetty(100, false), couleurFond: '#3B82F6', jours: {1:true,2:true,3:true,4:true,5:true} });
  
  const [formPoste, setFormPoste] = useState({
    nom: '', couleur: '#8B5CF6', qte: 1, slots: [{ id: Date.now(), start: '08:00', end: '12:00', days: { 1: true, 2: true, 3: true, 4: true, 5: true } }]
  });

  const handleAgentChange = (champ, valeur) => {
    const newAgent = { ...formAgent, [champ]: valeur };
    if (champ === 'quotite' || champ === 'estEtudiant') {
      newAgent.hContrat = calculerContratBetty(newAgent.quotite, newAgent.estEtudiant);
    }
    setFormAgent(newAgent);
  };

  const autoGenerateDates = async () => {
    setIsFetchingDates(true);
    const year1 = anneeScolaireDeBase; 
    const year2 = anneeScolaireDeBase + 1;
    let nouvellesPeriodes = [];
    
    const feriesY1 = getJoursFerie(year1).filter(f => f.date >= `${year1}-08-15`);
    const feriesY2 = getJoursFerie(year2).filter(f => f.date <= `${year2}-08-15`);
    nouvellesPeriodes = [...feriesY1, ...feriesY2].map(f => ({ 
      id: `ferie_${Date.now()}_${Math.random()}`, nom: f.nom, debut: f.date, fin: f.date, type: 'ferie'
    }));

    nouvellesPeriodes.push({
      id: `vac_pre_${Date.now()}`, nom: "Vacances d'Été (Pré-rentrée)", debut: `${year1}-07-01`, fin: `${year1}-08-31`, type: 'vacances'
    });

    try {
      const zoneFormattee = zone.replace(' ', '+');
      const urlApi = `https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-calendrier-scolaire/records?limit=100&refine=zones%3A${zoneFormattee}&refine=annee_scolaire%3A${year1}-${year2}`;
      const res = await fetch(urlApi);
      const data = await res.json();
      
      let vacs = (data.results || [])
        .filter(r => !r.population || !r.population.toLowerCase().includes("enseignant"))
        .filter(r => r.description && r.description.toLowerCase().includes("vacances"))
        .map(r => {
           const endD = new Date(r.end_date); 
           endD.setDate(endD.getDate() - 1);
           const pad = n => String(n).padStart(2, '0');
           return { 
             id: `vac_${Date.now()}_${Math.random()}`, nom: r.description, debut: r.start_date.split('T')[0], fin: `${endD.getFullYear()}-${pad(endD.getMonth()+1)}-${pad(endD.getDate())}`, type: 'vacances'
           };
        });

      vacs = Array.from(new Map(vacs.map(item => [item.debut, item])).values());
      vacs = vacs.map(v => {
        if (v.nom.toLowerCase().includes("été") && v.fin < `${year2}-08-31`) {
          return { ...v, fin: `${year2}-08-31` };
        }
        return v;
      });

      if (vacs.length === 0 && year1 === 2026) {
         const fallback = [
           { nom: "Vacances de la Toussaint", debut: "2026-10-17", fin: "2026-11-01" }, { nom: "Vacances de Noël", debut: "2026-12-19", fin: "2027-01-03" },
           { nom: "Vacances d'Hiver", debut: zone.includes("A") ? "2027-02-06" : (zone.includes("B") ? "2027-02-13" : "2027-02-20"), fin: zone.includes("A") ? "2027-02-21" : (zone.includes("B") ? "2027-02-28" : "2027-03-07") },
           { nom: "Vacances de Printemps", debut: zone.includes("A") ? "2027-04-10" : (zone.includes("B") ? "2027-04-17" : "2027-04-24"), fin: zone.includes("A") ? "2027-04-25" : (zone.includes("B") ? "2027-05-02" : "2027-05-09") },
           { nom: "Vacances d'Été", debut: "2027-07-07", fin: "2027-08-31" }
         ];
         vacs = fallback.map(f => ({ id: `fallback_${Date.now()}_${Math.random()}`, nom: f.nom, debut: f.debut, fin: f.fin, type: 'vacances' }));
      }

      nouvellesPeriodes = [...nouvellesPeriodes, ...vacs];
    } catch (e) {
      alert("Erreur de connexion. Seuls les jours fériés fixes ont pu être ajoutés.");
    }
    
    setPeriodes(nouvellesPeriodes.sort((a,b) => a.debut.localeCompare(b.debut)));
    setIsFetchingDates(false);
  };

  const finishSetup = () => {
    localStorage.setItem('edt-periodes', JSON.stringify(periodes));
    localStorage.setItem('edt-agents', JSON.stringify(agents));
    localStorage.setItem('edt-postes', JSON.stringify(postes));
    localStorage.setItem('edt-dotation', dotation.toString());
    
    const baseDate = new Date(`${anneeScolaireDeBase}-09-01`);
    const day = baseDate.getDay() || 7; 
    baseDate.setDate(baseDate.getDate() - (day - 1));
    const pad = n => String(n).padStart(2, '0');
    const startStr = `${baseDate.getFullYear()}-${pad(baseDate.getMonth()+1)}-${pad(baseDate.getDate())}`;

    const initialBesoins = [];
    const baseMonday = new Date(startStr);

    postes.forEach(p => {
      if (p.slots && p.slots.length > 0) {
        p.slots.forEach(slot => {
          if (slot.start && slot.end) {
            [1, 2, 3, 4, 5].forEach(dayIndex => {
              if (slot.days[dayIndex]) {
                const d = new Date(baseMonday);
                d.setDate(d.getDate() + dayIndex - 1);
                const dateStr = `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;

                initialBesoins.push({
                  id: String(Date.now() + Math.random()),
                  start: `${dateStr}T${slot.start}:00`,
                  end: `${dateStr}T${slot.end}:00`,
                  extendedProps: { posteId: p.id, posteNom: p.nom, qte: Number(p.qte) || 1 }
                });
              }
            });
          }
        });
      }
    });

    localStorage.setItem('edt-template-versions', JSON.stringify([{ id: 1, nom: "Modèle Initial", dateDebut: startStr, events: [], besoins: initialBesoins, statut: 'brouillon' }]));
    localStorage.setItem('edt-setup-done', 'true');
    onComplete();
  };

  // NOUVELLE FONCTION POUR L'IMPORT DEPUIS LE WIZARD
  const handleWizardImport = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target.result);
        executeImport(data);
        alert("Sauvegarde restaurée avec succès !");
        // On signale directement à React que c'est fini sans avoir besoin de recharger la page
        onComplete();
      } catch (err) {
        alert("Erreur lors de la lecture du fichier JSON.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className={`min-h-screen ${t.bgMain} flex flex-col items-center py-12 px-4 transition-colors`}>
      <div className={`w-full max-w-2xl ${t.cardBg} rounded-xl shadow-xl overflow-hidden border border-black/5`}>
        <div className={`${t.headerBg} p-6 ${t.headerText} text-center`}>
          <h1 className="text-3xl font-black tracking-wider">Planning CPE</h1><p className="opacity-80 mt-1">Configuration Initiale ({step}/4)</p>
        </div>
        <div className="p-8">
          {step === 1 && (
            <div className="text-center space-y-6">
              <h2 className={`text-2xl font-bold ${t.header}`}>Bienvenue !</h2>
              <p className="text-gray-500">Souhaitez-vous importer une sauvegarde existante ou paramétrer une nouvelle année scolaire ?</p>
              <div className="grid grid-cols-2 gap-4 mt-8">
                <button onClick={() => document.getElementById('import-init').click()} className="p-6 border-2 border-dashed border-emerald-500 rounded-xl hover:bg-emerald-500/10 transition group"><div className="text-4xl mb-2 group-hover:scale-110 transition">⬆️</div><div className="font-bold text-emerald-600">Importer JSON</div></button>
                <input type="file" id="import-init" accept=".json" onChange={handleWizardImport} className="hidden" />
                <button onClick={() => setStep(2)} className={`p-6 border-2 border-transparent ${t.bgLight} transition group hover:brightness-95 rounded-xl`}><div className="text-4xl mb-2 group-hover:scale-110 transition">✨</div><div className={`font-bold ${t.header}`}>Nouvelle Année</div></button>
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="space-y-6 animate-in fade-in">
              <h2 className={`text-xl font-bold ${t.header} border-b pb-2`}>1. Vacances & Jours Fériés</h2>
              <p className="text-sm text-gray-500">Générez automatiquement toutes les dates de fermeture en choisissant votre zone et l'année de rentrée.</p>
              
              <div className={`flex gap-4 p-4 ${t.bgLight} border ${t.borderLight} rounded-xl items-end shadow-inner`}>
                <div className="w-1/4"><label className={`text-xs font-bold ${t.header} block mb-1`}>Année Rentrée</label><input type="number" value={anneeScolaireDeBase} onChange={e=>setAnneeScolaireDeBase(Number(e.target.value))} className="w-full p-2 rounded border bg-transparent" /></div>
                <div className="flex-1"><label className={`text-xs font-bold ${t.header} block mb-1`}>Zone Académique</label><select value={zone} onChange={e=>setZone(e.target.value)} className="w-full p-2 rounded border bg-transparent"><option value="Zone A">Zone A</option><option value="Zone B">Zone B</option><option value="Zone C">Zone C</option><option value="Corse">Corse</option></select></div>
                <div><button onClick={autoGenerateDates} disabled={isFetchingDates} className={`${t.btnPrimary} px-4 py-2 rounded font-bold shadow disabled:opacity-50`}>{isFetchingDates ? '⏳ Calcul...' : '⚡ Générer'}</button></div>
              </div>
              
              <ul className="space-y-2 max-h-48 overflow-y-auto p-2 rounded border border-black/10">
                {periodes.length === 0 && <p className="text-xs text-gray-500 italic text-center py-4">Aucune date configurée.</p>}
                {periodes.map(p => ( 
                  <li key={p.id} className={`flex justify-between items-center ${t.bgLight} p-2 rounded shadow-sm text-sm border ${t.borderLight}`}>
                    <span className="font-bold text-gray-700">{p.nom} 
                      <span className={`ml-2 px-2 py-0.5 rounded text-[10px] uppercase font-bold text-white ${p.type === 'ferie' ? 'bg-green-600' : 'bg-blue-600'}`}>
                        {p.type === 'ferie' ? 'Férié (Payé)' : 'Vacances (0h)'}
                      </span>
                      <span className="font-normal text-gray-500 text-xs ml-2">({p.debut}{p.debut !== p.fin ? ` au ${p.fin}` : ''})</span>
                    </span>
                    <button onClick={() => setPeriodes(periodes.filter(x => x.id !== p.id))} className="text-red-500 hover:text-red-700 font-bold px-2">✖</button>
                  </li> 
                ))}
              </ul>

              <div className="flex gap-2 border-t border-black/10 pt-4 flex-wrap">
                <input type="text" placeholder="Ajout manuel..." value={formPeriode.nom} onChange={e=>setFormPeriode({...formPeriode, nom: e.target.value})} className="flex-1 border p-2 rounded text-sm min-w-[150px] bg-transparent" />
                <select value={formPeriode.type} onChange={e=>setFormPeriode({...formPeriode, type: e.target.value})} className="border p-2 rounded text-sm w-32 bg-transparent">
                  <option value="vacances">Vacances</option>
                  <option value="ferie">Férié</option>
                </select>
                <input type="date" value={formPeriode.debut} onChange={e=>setFormPeriode({...formPeriode, debut: e.target.value})} className="border p-2 rounded text-sm w-32 bg-transparent" />
                <input type="date" value={formPeriode.fin} onChange={e=>setFormPeriode({...formPeriode, fin: e.target.value})} className="border p-2 rounded text-sm w-32 bg-transparent" />
                <button onClick={() => { if(formPeriode.nom && formPeriode.debut) { setPeriodes([...periodes, {id: Date.now(), ...formPeriode}].sort((a,b) => a.debut.localeCompare(b.debut))); setFormPeriode({nom:'', debut:'', fin:'', type:'vacances'}); } }} className={`${t.btnPrimary} px-3 rounded font-bold`}>+</button>
              </div>

              <div className="flex justify-between pt-4 mt-4 border-t border-black/10"><button onClick={() => setStep(1)} className="text-gray-500 font-bold px-4 py-2">⬅ Retour</button><button onClick={() => setStep(3)} className={`${t.btnPrimary} px-6 py-2 rounded-lg font-bold shadow`}>Suivant ➔</button></div>
            </div>
          )}

          {step === 3 && (() => {
            const totalETP = Math.round(agents.reduce((sum, a) => sum + Number(a.quotite), 0)) / 100;
            const isOverflow = dotation > 0 && totalETP > dotation;
            const isExact = dotation > 0 && totalETP === dotation;

            return (
              <div className="space-y-6 animate-in fade-in">
                <h2 className={`text-xl font-bold ${t.header} border-b pb-2`}>2. Équipe AED & Dotation</h2>
                <p className="text-sm text-gray-500">Saisissez la dotation globale de votre établissement, puis ajoutez les agents.</p>
                
                <div className={`p-5 rounded-xl border flex justify-between items-center transition-all ${isOverflow ? 'bg-red-900/10 border-red-500/50' : `${t.bgLight} ${t.borderLight} shadow-sm`}`}>
                  <div>
                    <label className={`text-[10px] font-bold ${t.header} uppercase tracking-wider block mb-1`}>Dotation Globale (Budget)</label>
                    <div className="flex items-center gap-2">
                      <input type="number" step="0.5" value={dotation || ''} onChange={e => setDotation(parseFloat(e.target.value) || 0)} placeholder="Ex: 5.5" className={`border ${t.borderLight} p-2 w-24 text-center rounded-lg font-black text-2xl ${t.header} bg-transparent outline-none focus:ring-2 transition-all`} />
                      <span className="font-bold text-gray-500">ETP</span>
                    </div>
                  </div>
                  
                  <div className="text-right flex flex-col justify-center">
                    <label className={`text-[10px] font-bold ${t.header} uppercase tracking-wider block mb-1`}>Budget Consommé</label>
                    <div className="flex items-end justify-end gap-1">
                      <span className={`text-4xl font-black leading-none ${isOverflow ? 'text-red-500' : (isExact ? 'text-emerald-500' : t.textAccent)}`}>
                        {totalETP.toFixed(2)}
                      </span>
                      <span className="text-sm font-bold text-gray-500 mb-1">/ {dotation || '?'} ETP</span>
                    </div>
                  </div>
                </div>

                <div className={`${t.bgLight} p-4 rounded-xl border ${t.borderLight} grid grid-cols-12 gap-3 items-end`}>
                  <div className="col-span-4"><label className={`text-[10px] font-bold ${t.header} uppercase`}>Nom</label><input type="text" value={formAgent.nom} onChange={e=>handleAgentChange('nom', e.target.value)} className="w-full p-2 text-sm rounded border bg-transparent" placeholder="Ex: Célia" /></div>
                  <div className="col-span-2"><label className={`text-[10px] font-bold ${t.header} uppercase`}>Quot. (%)</label><input type="number" step="0.1" value={formAgent.quotite} onChange={e=>handleAgentChange('quotite', e.target.value)} className="w-full p-2 text-sm rounded border bg-transparent font-bold text-center" /></div>
                  <div className="col-span-3 flex items-center justify-center pb-2"><label className={`flex items-center gap-1 text-[10px] font-bold ${t.header} cursor-pointer bg-transparent px-2 py-1.5 border rounded shadow-sm`}><input type="checkbox" checked={formAgent.estEtudiant} onChange={e=>handleAgentChange('estEtudiant', e.target.checked)} className="w-3 h-3" />🎓 Étudiant</label></div>
                  <div className="col-span-3"><label className={`text-[10px] font-bold ${t.header} uppercase`}>Contrat</label><input type="text" value={typeof formAgent.hContrat === 'number' ? formatHeureMinutes(formAgent.hContrat) : formAgent.hContrat} onChange={e=>setFormAgent({...formAgent, hContrat: e.target.value})} onBlur={e=>setFormAgent({...formAgent, hContrat: parseHeureSaisie(e.target.value)})} className="w-full p-2 text-sm rounded border font-mono text-center bg-transparent" /></div>
                  
                  <div className="col-span-2"><label className={`text-[10px] font-bold ${t.header} uppercase`}>Coul.</label><input type="color" value={formAgent.couleurFond} onChange={e=>setFormAgent({...formAgent, couleurFond: e.target.value})} className="w-full h-9 rounded cursor-pointer p-0 border-0" /></div>
                  <div className="col-span-10 mt-1">
                    <button type="button" onClick={() => { if(formAgent.nom) { const hC = typeof formAgent.hContrat === 'string' ? parseHeureSaisie(formAgent.hContrat) : formAgent.hContrat; setAgents([...agents, {id: Date.now(), nom: formAgent.nom, quotite: parseFloat(formAgent.quotite), estEtudiant: formAgent.estEtudiant, hContrat: hC, couleurFond: formAgent.couleurFond, jours: formAgent.jours}]); setFormAgent({...formAgent, nom: '', estEtudiant: false}); } }} className={`w-full ${t.btnPrimary} px-4 py-2 rounded text-sm font-bold shadow`}>Ajouter cet agent</button>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2">
                  {agents.map(a => (
                    <span key={a.id} className="text-sm font-bold px-3 py-1 rounded-full flex items-center gap-2 shadow-sm" style={{ backgroundColor: a.couleurFond, color: getContrastYIQ(a.couleurFond) }}>
                      {a.nom} {a.estEtudiant && '🎓'} ({a.quotite}%) 
                      <button onClick={()=>setAgents(agents.filter(x=>x.id!==a.id))} className="hover:opacity-60 transition-opacity">✖</button>
                    </span>
                  ))}
                </div>

                <div className="flex justify-between pt-4 mt-8 border-t border-black/10"><button onClick={() => setStep(2)} className="text-gray-500 font-bold px-4 py-2">⬅ Retour</button><button onClick={() => setStep(4)} className={`${t.btnPrimary} px-6 py-2 rounded-lg font-bold shadow`}>Suivant ➔</button></div>
              </div>
            );
          })()}
          
          {step === 4 && (
            <div className="space-y-6 animate-in fade-in">
              <h2 className={`text-xl font-bold ${t.header} border-b pb-2`}>3. Postes & Grilles de Besoins</h2>
              <p className="text-sm text-gray-500">Définissez les postes clés et configurez leurs plages horaires récurrentes.</p>
              
              <div className={`p-4 rounded-xl border ${t.borderLight} ${t.bgLight} space-y-3`}>
                <div className="flex gap-3">
                  <div className="flex-[2]">
                    <label className={`text-[10px] font-bold ${t.header} uppercase block mb-1`}>Nom du poste</label>
                    <input type="text" placeholder="Ex: Loge, Cantine..." value={formPoste.nom} onChange={e=>setFormPoste({...formPoste, nom: e.target.value})} className="w-full border rounded p-2 text-sm bg-transparent font-bold" />
                  </div>
                  <div className="w-24">
                    <label className={`text-[10px] font-bold ${t.header} uppercase block mb-1`}>Effectif</label>
                    <input type="number" min="1" value={formPoste.qte} onChange={e=>setFormPoste({...formPoste, qte: e.target.value})} className="w-full border rounded p-2 text-sm text-center font-bold bg-transparent" />
                  </div>
                  <div>
                    <label className={`text-[10px] font-bold ${t.header} uppercase block mb-1`}>Couleur</label>
                    <input type="color" value={formPoste.couleur} onChange={e=>setFormPoste({...formPoste, couleur: e.target.value})} className="w-10 h-10 rounded cursor-pointer p-0 border-0" />
                  </div>
                </div>

                <div className="border-t border-black/10 pt-3">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-bold text-gray-500 uppercase">Plages horaires (Semaine type)</span>
                    <button type="button" onClick={() => setFormPoste({...formPoste, slots: [...formPoste.slots, { id: Date.now(), start: '08:00', end: '12:00', days: { 1: true, 2: true, 3: true, 4: true, 5: true } }]})} className="text-xs bg-black/10 hover:bg-black/20 px-2 py-1 rounded font-bold">➕ Plage</button>
                  </div>
                  <div className="space-y-2 max-h-40 overflow-y-auto pr-1">
                    {formPoste.slots.map((slot, idx) => (
                      <div key={idx} className={`p-2 rounded border ${t.borderLight} ${t.cardBg} flex flex-col gap-1.5`}>
                        <div className="flex items-center gap-2">
                          <input type="time" required value={slot.start} onChange={e => {
                            const ns = [...formPoste.slots]; ns[idx].start = e.target.value; setFormPoste({...formPoste, slots: ns});
                          }} className="border p-1 text-xs rounded bg-transparent w-24 text-center font-bold" />
                          <span className="text-gray-400 text-xs">à</span>
                          <input type="time" required value={slot.end} onChange={e => {
                            const ns = [...formPoste.slots]; ns[idx].end = e.target.value; setFormPoste({...formPoste, slots: ns});
                          }} className="border p-1 text-xs rounded bg-transparent w-24 text-center font-bold" />
                          <button type="button" onClick={() => {
                            const ns = [...formPoste.slots]; ns.splice(idx, 1); setFormPoste({...formPoste, slots: ns});
                          }} className="text-red-500 font-bold text-xs ml-auto">✖</button>
                        </div>
                        <div className="flex gap-1">
                          {[1, 2, 3, 4, 5].map(day => (
                            <label key={day} className={`flex-1 flex items-center justify-center py-0.5 rounded border text-[10px] font-bold cursor-pointer ${slot.days[day] ? `${t.btnPrimary} border-transparent` : 'bg-transparent text-gray-500 border-black/10'}`}>
                              <input type="checkbox" className="hidden" checked={slot.days[day]} onChange={e => {
                                const ns = [...formPoste.slots]; ns[idx].days[day] = e.target.checked; setFormPoste({...formPoste, slots: ns});
                              }} />
                              {nomsJours[day % 7]}
                            </label>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <button type="button" onClick={() => {
                  if(formPoste.nom) {
                    setPostes([...postes, { id: Date.now(), ...formPoste, qte: Number(formPoste.qte) || 1 }]);
                    setFormPoste({ nom: '', couleur: '#8B5CF6', qte: 1, slots: [{ id: Date.now(), start: '08:00', end: '12:00', days: { 1: true, 2: true, 3: true, 4: true, 5: true } }] });
                  }
                }} className={`w-full ${t.btnPrimary} py-2 rounded text-sm font-bold shadow mt-2`}>Ajouter ce poste</button>
              </div>

              <div className="flex flex-wrap gap-2">
                {postes.map(p => (
                  <span key={p.id} className="text-sm font-bold px-3 py-1 rounded-full flex items-center gap-2 shadow-sm" style={{ backgroundColor: p.couleur, color: getContrastYIQ(p.couleur) }}>
                    {p.nom} ({p.qte} pers., {p.slots?.length || 0} plage(s)) 
                    <button onClick={()=>setPostes(postes.filter(x=>x.id!==p.id))} className="hover:opacity-60 transition-opacity">✖</button>
                  </span>
                ))}
              </div>

              <div className="flex justify-between pt-4 mt-8 border-t border-black/10">
                <button onClick={() => setStep(3)} className="text-gray-500 font-bold px-4 py-2">⬅ Retour</button>
                <button onClick={finishSetup} className={`${t.btnPrimary} px-8 py-3 rounded-lg font-black shadow-lg text-lg animate-pulse`}>Lancer l'Application 🚀</button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};